# Challenge 1 - 문제 1: Git 저장소 인증 실패

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: challenge-app-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/invalid-user-12345/k8s-gitops-demo.git
    targetRevision: main
    path: apps/demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: day5-challenge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
