# Challenge 1 - 문제 4: 동기화 정책 문제
# 의도적 오류: Auto-sync가 비활성화됨

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: challenge-app-4
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<username>/k8s-gitops-demo.git  # <username>을 본인 것으로 변경
    targetRevision: main
    path: apps/demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: day5-challenge
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # 오류: automated 섹션이 없음 (Auto-sync 비활성화)

# 해결 방법:
# automated 섹션 추가하여 Auto-sync 활성화
#
# kubectl patch application challenge-app-4 -n argocd --type merge \
#   -p '{"spec":{"syncPolicy":{"automated":{"prune":true,"selfHeal":true}}}}'
#
# 또는 전체 Application 재배포:
# syncPolicy:
#   automated:
#     prune: true
#     selfHeal: true
#   syncOptions:
#   - CreateNamespace=true
