apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
  namespace: day2-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: python:3.13
        command: ["sleep", "3600"]
        resources:
          requests:
            cpu: 5000m
            memory: 8Gi
          limits:
            cpu: 8000m
            memory: 16Gi
