apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  namespace: challenge1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-v2
  template:
    metadata:
      labels:
        app: frontend-v2
    spec:
      containers:
      - name: nginx
        image: nginx:nonexistent-tag
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
