apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: day1-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.62
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: day1-challenge
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: backend-wrong
    version: v1
