apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: day1-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_DB
          value: "webstart"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "password123"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: day1-challenge
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: database
