apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: lab2-workloads
  labels:
    app: web
    tier: frontend
    created-by: lab1
spec:
  containers:
  - name: nginx
    image: nginx:1.20
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
