apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: kubernetes-backend
  namespace: production
spec:
  provider:
    kubernetes:
      remoteNamespace: vault
      auth:
        serviceAccount:
          name: external-secrets-sa
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt