# Week 3 Day 4 Challenge 1 - 문제 4: Secret 노출
# 의도적 오류:
# 1. ConfigMap에 API 키와 데이터베이스 URL 저장
# 2. Deployment에 평문 비밀번호 환경변수
# 3. ConfigMap에서 민감 정보 참조

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: securebank
data:
  api-key: "sk-1234567890abcdef"  # 의도적 오류: API 키를 ConfigMap에 저장
  database-url: "postgresql://admin:password123@database:5432/securebank"  # 의도적 오류: 평문 비밀번호
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: securebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      tier: api
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      serviceAccountName: developer-sa
      containers:
      - name: backend
        image: nginx:alpine
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_PASSWORD
          value: "supersecret123"  # 의도적 오류: 평문 비밀번호
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: securebank
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
