# 문제 3: PVC 바인딩 실패 - 불가능한 스토리지 요청

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-storage
  namespace: day3-challenge
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Ti
  storageClassName: nonexistent-storage
