# 문제 4: 네트워크 정책 차단 - 라벨 불일치

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-policy
  namespace: day3-challenge
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: wrong-backend
    ports:
    - protocol: TCP
      port: 5432
