# 문제 1: DNS 해결 실패 - 잘못된 서비스 이름

apiVersion: v1
kind: Service
metadata:
  name: wrong-backend-service  # 의도적 오류: 잘못된 서비스 이름
  namespace: day3-challenge
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 80

# 문제: 프론트엔드는 'backend-service'를 찾지만 실제로는 'wrong-backend-service'로 생성됨
# 해결: 서비스 이름을 'backend-service'로 수정하거나 새로운 서비스 생성
