apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: user-service
spec:
  host: user-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      ver: v2  # 🐛 BUG: 태그 오류
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
