name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Test Backend
        run: |
          cd backend
          npm ci
          npm test
      
      - name: Test Frontend
        run: |
          cd frontend
          npm ci
          CI=true npm test

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build Frontend
        run: |
          cd frontend
          docker build -t frontend:${{ github.sha }} .
      
      - name: Build Backend
        run: |
          cd backend
          docker build -t backend:${{ github.sha }} .
      
      - name: Test Docker Images
        run: |
          docker run -d --name test-backend backend:${{ github.sha }}
          sleep 5
          docker logs test-backend
          docker stop test-backend

  deploy:
    name: Deploy Notification
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deployment Success
        run: |
          echo "🚀 Deployment successful!"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"
